/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutComponent: typeof import('./src/components/AboutComponent.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ArchiveCardComponent: typeof import('./src/components/ArchiveCardComponent.vue')['default']
    ContactIconsComponent: typeof import('./src/components/ContactIconsComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IntroductionsComponent: typeof import('./src/components/IntroductionsComponent.vue')['default']
    MenuDashboard: typeof import('./src/components/MenuDashboard.vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    ProjectCardsComponent: typeof import('./src/components/ProjectCardsComponent.vue')['default']
    ProjectDivComponent: typeof import('./src/components/ProjectDivComponent.vue')['default']
    ProjectsComponent: typeof import('./src/components/ProjectsComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
